remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "Open on GitHub":
    - "//github.com/bpiyush/ml-engg-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
